package com.roadpadi_authentication.signup_signin.model;

public enum RoleEnum {

    ROLE_TRANSPORT_COMPANY,
    ROLE_TRANSPORT_COMPANY_TERMINAL_MANAGER,
    ROLE_TRANSPORT_COMPANY_BOOKING_ADMIN,
    ROLE_TRANSPORT_COMPANY_DRIVER,
    ROLE_CUSTOMER,
    ROLE_OTHER_COMPANY,
    ROLE_CUSTOMER_HELPER,
    ROLE_FUEL_STATION,
    ROLE_FUEL_STATION_MANAGER,
    ROLE_FUEL_STATION_ATTENDANT,
    ROLE_SUPER_ADMIN

}
